Update unratedTaskTable styles to match Figma design
Vincit/VISDOM-Roadmapper pull request #103
Opened 2021-07-12 07:27 UTC by PatricKangasmaki

2021-07-12 11:48 UTC, IidaKainu requested changes
The unratedTaskTable looks just like Figma's 👍 
Just a few things I noticed that could be cleared up

2021-07-12 11:48 UTC, IidaKainu commented on frontend/src/components/TableUnratedTaskRow.tsx
> +  const taskDetailsClicked = (e: React.MouseEvent<any, MouseEvent>) => {
Both taskDetailsClicked and rateTaskClicked could use openModal
```
const openModal = (modalType: ModalTypes) => (e: React.SyntheticEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dispatch(
      modalsActions.showModal({
        modalType,
        modalProps: {
          taskId: task.id,
        },
      }),
    );
  };
```
The modal type would be sent on event handlers
`onClick={openModal(ModalTypes.TASK_INFO_MODAL)}`
`onClick={openModal(ModalTypes.RATE_TASK_MODAL)}`

2021-07-12 11:48 UTC, IidaKainu commented on frontend/src/components/TableUnratedTaskRow.tsx
>                taskId: task.id,
I am not sure if this link is needed (the correct url is shown without it too), but shouldn't the ModalTypes be RATE_TASK_MODAL?

2021-07-13 06:05 UTC, PatricKangasmaki commented
I added all your suggestions and tested the functionalities again (everything works as wanted) 👍

2021-07-13 06:43 UTC, IidaKainu approved these changes

2021-07-13 08:39 UTC, merged