Add view for 'no projects yet' -page
Vincit/VISDOM-Roadmapper pull request #122
Opened 2021-07-29 08:34 UTC by PatricKangasmaki

2021-07-29 08:51 UTC, IidaKainu requested changes
Looks good!
There's some similar css in create project, login and register pages (white container/formDiv, footer). They could be combined 👍

2021-07-29 08:51 UTC, IidaKainu commented on frontend/src/pages/CreateProjectPage.tsx
> +            <Trans i18nKey="First project info 1/2" />
Looks like a typo: the first info is repeated twice
```suggestion
            <Trans i18nKey="First project info 2/2" />
```

2021-07-29 10:13 UTC, PatricKangasmaki commented
Fixed the typo and moved css-classes that were used in multiple places to the shared.scss folder 👍 I left the footer in the createProject-page module untouched since it has its own translations and positions

2021-07-29 11:13 UTC, juhoeerola requested changes

2021-07-29 11:13 UTC, juhoeerola commented on frontend/src/components/LoginNavBar.tsx
> +    {type === 'register' && (
These could maybe be combined
```suggestion
    {(type === 'register' || type === 'landing') && (
```

2021-07-29 11:13 UTC, juhoeerola commented on frontend/src/components/NavBar.tsx
> +      {userInfo &&
I think this whole component could be refactored a bit

Using couple conditional early returns would make this much clearer in my opinion, e.g.

```ts
  if (!userInfo) {
    return pathname.startsWith(paths.loginPage) ? (
      <LoginNavBar type="login" />
    ) : (
      <LoginNavBar type="register" />
    );
  }

  if (pathname.startsWith(paths.getStarted))
    return <LoginNavBar type="getStarted" />;

  return (
    <div className={classes(css.navBarDiv)}>
      <CornerPiece />
      <div className={classes(css.navBarRightSide)}>
        <div className={classes(css.navBarText)}>
          <Trans i18nKey="Project" />
        </div>
        <RoadmapSelectorWidget />
        <div className={classes(css.navBarDivider)} />
        <Link className={classes(css.navBarLink)} to={paths.userInfo}>
          <PermIdentityIcon className={classes(css.icon)} />
        </Link>
        <Link className={classes(css.navBarLink)} to={paths.logoutPage}>
          <PowerSettingsNewIcon className={classes(css.icon)} />
        </Link>
      </div>
    </div>
  );
```

2021-07-29 12:41 UTC, PatricKangasmaki commented
Added all your suggestions!

2021-07-29 12:47 UTC, juhoeerola approved these changes
Look good 👍 

Which ever is merged later, this or #116, can add the functionality to the "Create new project" button

2021-07-30 05:35 UTC, IidaKainu approved these changes
👍

2021-08-03 07:39 UTC, merged