Use virtualised list for task table
Vincit/VISDOM-Roadmapper pull request #139
Opened 2021-08-17 08:55 UTC by juhoeerola

Also moved the task filtering out from the task table component.
It is now the user's responsibility to select which tasks should be
shown.

2021-08-17 12:10 UTC, IidaKainu reviewed
I'll drop a single suggestion since I am unable to do a full review today

2021-08-18 07:03 UTC, IidaKainu requested changes
Excluding the previous suggestion (which is why this is submitted as 'request changes') I have not much to comment on. I learned a lot from reading the code and this is obviously well executed. 🔥

2021-08-18 07:15 UTC, juhoeerola commented on frontend/src/components/TaskTable.tsx
> +        height={600}
Good catch, also made the height and row height parameters

2021-08-18 07:18 UTC, juhoeerola commented
Noticed that Roadmap.users could be undefined, so added that to the type

2021-08-18 08:56 UTC, IidaKainu approved these changes

2021-08-18 09:45 UTC, merged