Task util refactor
Vincit/VISDOM-Roadmapper pull request #142
Opened 2021-08-20 11:59 UTC by juhoeerola

- started to rewrite / reorganise task utils into (hopefully) reusable predicates
- rewrote sorting to
  - use decorate-sort-undecorate automaitcally for calculated keys
  - allow object property key as sorting key
  - use `undefined` as `NO_SORT`
- added `useSorting()` hook & SortingArrow component

2021-08-30 13:23 UTC, IidaKainu requested changes
Really neat refactor! Although generics complicate reading of the implementations (took a while to understand😅), the solutions are 100% improvements.

I have only a few naming suggestions, otherwise this is good to go 🔥

2021-08-30 13:23 UTC, IidaKainu commented on frontend/src/utils/SortUtils.ts
> +export type Sort<T, K = any> =
Would the name 'SortBy' suit this type better? Currently there's a sort function and Sort type, which may be a bit confusing

```suggestion
export type SortBy<T, K = any> =
```

2021-08-30 13:23 UTC, IidaKainu commented on frontend/src/utils/TaskUtils.ts
> +    const reps = user.representativeFor?.filter(
Clients or customers would describe the value better
```suggestion
    const clients = user.representativeFor?.filter(
```

2021-08-30 13:23 UTC, IidaKainu commented on frontend/src/utils/TaskUtils.ts
> +    const represented = roadmap.customers?.filter((customer) =>
Maybe clients or customers would suit better here too (at least I thought 'wait who are represented' for a second)
```suggestion
    const clients = roadmap.customers?.filter((customer) =>
```

2021-08-31 09:24 UTC, juhoeerola commented
Thanks, those are arguably better names

Added the suggestions

2021-08-31 09:26 UTC, IidaKainu approved these changes

2021-08-31 09:57 UTC, merged