Remove local planner weights
Vincit/VISDOM-Roadmapper pull request #151
Opened 2021-08-27 09:49 UTC by IidaKainu

Since only admins see the planner page and only few might be present in a roadmap, the edition of user weights is saved instantaneously.

2021-09-01 09:35 UTC, IidaKainu commented
- rebased the branch on top of master
- removed the tooltip from the planner weights page as the description is already written on the page (I can also move the info into the tooltip if it's preferable)

2021-09-03 13:16 UTC, juhoeerola requested changes
Looks great 👍 

just a couple suggestions

2021-09-03 13:16 UTC, juhoeerola commented on frontend/src/pages/PlannerWeightsPage.tsx
> +      localCustomers!.map((customer) =>
It's better to provide update function to set state, when the previous state needs to be referenced,
this way e.g. batched updates work reliably
```suggestion
    setLocalCustomers((previous) =>
      previous!.map((customer) =>
```

2021-09-06 06:45 UTC, IidaKainu commented
Added the suggestions 👍 

> provide update function to set state, when the previous state needs to be referenced

Feels a bit surprising I have missed such a fundamental part about the useState hook. I need to do some documentation reading 😄

2021-09-08 07:21 UTC, juhoeerola approved these changes

2021-09-09 08:04 UTC, merged