Visual fixes to Overview pages and EditableText
Vincit/VISDOM-Roadmapper pull request #193
Opened 2021-11-04 10:01 UTC by AleksiKytola

2021-11-04 11:22 UTC, PatricKangasmaki requested changes
This is looking great! 👍 There were a few things that I found:

If I recall correctly, there was some talk in weekly some time ago about not displaying the title twice (example in pic). Should it be changed or is this okay?

![image](https://user-images.githubusercontent.com/80753884/140303843-56f46d8e-79a8-446f-90ab-a4899d5b4a11.png)

Some text overflow checks would be nice add as well, they're currently breaking badly (Editing works well, the textfield expands and you can write on multiple lines):

![image](https://user-images.githubusercontent.com/80753884/140304568-4fa63a4c-300e-4ed2-bc9c-0af73c1c379a.png)

**EDIT:**

Just noticed that the overflow is only a problem when the words are too long. Otherwise it seems to work nicely 👍 It would be good to address this corner case anyways. I think it would be better if the absurdly long words would be under the other elements / have invisible overflow / be on multiple lines like other texts if this were to happen instead of going over them and making it look messy

2021-11-04 11:22 UTC, PatricKangasmaki commented on frontend/src/components/EditableText.module.scss
> +  padding-right: 21px;
You could shorten these to:

`margin: 14px 0px;`
`padding: 0px 21px`

2021-11-04 11:51 UTC, juhoeerola commented
Some combination of
```css
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  max-width: 40ch;
```
could work nicely for the text.

The ellipsis doesn't work with `display: flex;` though, so if that would be used it would need inner container for the text.

2021-11-05 11:46 UTC, AleksiKytola commented
![image](https://user-images.githubusercontent.com/65648793/140505608-e35f5c1c-823f-4ce5-b604-65d9ffc28f5e.png)
Added overflow: hidden to avoid text overflowing. Do note that the text only overflows if its a long text with no spaces interrupting since the word-wrap property of the element only allows the text to wrap between words. So in a typical use case it works as expected

2021-11-05 11:49 UTC, AleksiKytola commented
I didn't remove the duplicate title yet, as I think it looks fine this way and the only memory I have about removing duplicates was about removing the color dot from one of the fields in the customer overview

2021-11-07 15:03 UTC, IidaKainu reviewed
Sorry for not noticing the review request earlier. Found a minor thing to change, otherwise looks good 👍

2021-11-07 15:03 UTC, IidaKainu commented on frontend/src/pages/ClientOverviewPage.tsx
> +        value: <>{client.name}</>,
The option for jsx is mostly for styling purposes, so in this case the fragment can be left out
```suggestion
        value: client.name,
```

2021-11-08 08:31 UTC, merged