Add functionality for removing tasks through tasklist
Vincit/VISDOM-Roadmapper pull request #207
Opened 2021-11-19 14:44 UTC by PatricKangasmaki

Added similar deletion functionality for tasks as there are in clients. You can now delete tasks by clicking the trashcan icon in the task tables.

2021-11-22 08:10 UTC, AleksiKytola reviewed
Hyvältä näyttää muuten, ehkä ton arrowicon marginin voisi jättää poistamatta, omaan silmään ainakin näytti hyvältä sen kanssa :+1: :+1:

2021-11-22 08:10 UTC, AleksiKytola commented on frontend/src/shared.scss
> -    margin-left: 25px;
Tätä marginia ei mielestäni tarvitse poistaa

2021-11-23 10:17 UTC, PatricKangasmaki commented
Laitoin tuon marginin takaisin 👍

2021-11-23 13:12 UTC, IidaKainu requested changes
Delete-napit näkyy nyt muillekin kuin admineille: napin vois renderöidä roolin perusteella

2021-11-23 19:40 UTC, PatricKangasmaki commented
> Delete-napit näkyy nyt muillekin kuin admineille: napin vois renderöidä roolin perusteella

Hyvä huomio, ei ollu tullu ollenkaan mieleen tää 👍 Lisäisin nyt molempiin tauluihin delete-napeille usertyypille chekit että onko admin

2021-11-24 09:47 UTC, IidaKainu approved these changes

2021-11-24 09:47 UTC, IidaKainu commented on frontend/src/components/TaskTableRated.tsx
> +  const type = getType(userInfo, roadmapId);
Uusi userRoleSelector saattaisi olla tässä tapauksessa parempi vaihtoehto tyypin selvittämiseen

2021-11-25 08:18 UTC, merged