Email verification frontend
Vincit/VISDOM-Roadmapper pull request #209
Opened 2021-11-24 14:20 UTC by juhoeerola

2021-11-30 14:18 UTC, IidaKainu requested changes
Näyttää oikein hyvältä! Alla muutamia mietteitä / ehdotuksia:

Klikkailin verificationin läpi ja projektin luontivaiheessa huomasin, että alas jää erikoinen harmaa palkki. Taitaa olla Footer, mutta modaali on auki ja haalentaa värin? Tähän sopisi normaalisti näkyvä Footer, mutta en tiedä onko toivetta hankalakin toteuttaa / onko email verificationin scopessa
![image](https://user-images.githubusercontent.com/80758782/144062929-1e8ecf44-556a-4a4e-896b-8ce4ca1ac0c1.png)

2021-11-30 14:18 UTC, IidaKainu commented on frontend/src/pages/VerifyEmailPage.tsx
> +          </button>
Tähän sopisi latausikoni tms. requestin lähetyksen ajaksi. Jos ed. linkki on lähetetty samana päivänä mikään sivulla ei muutu, joka tuntui lievästi oudolta

2021-12-01 09:28 UTC, juhoeerola commented
Modaali tosiaan lisää tuollaisen taustan koko sivulle. Ehkä hämmentävämmän siitä tekee se, että nav bar näkyy normaalina (koska sillä on z-index 10).

Ei liene tämän scopessa. Mutta jos toteutetaan, niin olisi varmaankin parametri avattavalle modaalille, mutten tiedä onnistuuko.

2021-12-01 09:54 UTC, IidaKainu approved these changes

2021-12-01 10:00 UTC, IidaKainu commented
👍 
Lisäsin trelloon kortin modaalista, jottei unohtuisi

2021-12-01 11:27 UTC, merged