Invitation flow
Vincit/VISDOM-Roadmapper pull request #218
Opened 2021-12-12 12:07 UTC by IidaKainu

https://trello.com/c/iRRBRA7S/398-handling-of-expired-invite-links-in-frontend 
Refined the invitation frontend workflow

2021-12-12 12:28 UTC, IidaKainu commented on frontend/src/components/modals/JoinLinkNoAccessModal.tsx
> +  };
This function is used in all of the invitation modals. I wanted to provide it in the props (like closeModal) but could not figure out how

2021-12-16 09:57 UTC, juhoeerola requested changes

2021-12-16 09:57 UTC, juhoeerola commented on frontend/src/i18/english.ts
> +    'Project link unvalid': 'Project link unvalid',
```suggestion
    'Project link invalid': 'Project link invalid',
```

Shouldn't this be "invalid" not "unvalid"?

same in component naming

2021-12-16 09:57 UTC, juhoeerola commented on server/src/api/users/users.controller.ts
> +    .first();
```suggestion
    .findById(ctx.params.invitationId)
    .withGraphFetched('roadmap');
```

`findById` should work fine for this

2021-12-16 11:43 UTC, IidaKainu commented
Fixes added 🙏

2021-12-16 14:08 UTC, juhoeerola approved these changes
Looks good 👍 

maybe remove the `first()`, before merging

2021-12-16 14:08 UTC, juhoeerola commented on server/src/api/users/users.controller.ts
> +    .first();
```suggestion
    .withGraphFetched('roadmap');
```

`findById` returns (maximum) one item, so the first is redundant

2021-12-16 14:47 UTC, merged