Multiple task ratings
Vincit/VISDOM-Roadmapper pull request #227
Opened 2021-12-29 10:05 UTC by IidaKainu

Routes for adding/patching multiple ratings with one request. Either all or no ratings get added/patched.

2022-01-05 11:57 UTC, juhoeerola requested changes
Unless we use them, I'd remove the old singular routes.

Other than that, just few refactoring suggestions. The functionality seems good.

2022-01-05 11:57 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.routes.ts
> +  '/taskrating',
We could remove the singular versions of these routes. Or are these actually used somewhere?

2022-01-05 11:57 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +            await Task.relatedQuery('ratings', trx)
```suggestion
   (trx) =>
     Promise.all(
        ratings.map(
         ({ dimension, value, comment, forCustomer }: any) =>
           Task.relatedQuery('ratings', trx)
```

The `async () => await ...` can be simplified to `() => ...` which returns equivalent promise.

2022-01-05 11:57 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +            await rating.$query(trx).patchAndFetch({ value, comment }),
```suggestion
    (trx) =>
     Promise.all(
        foundRatings.map(
         ({ rating, value, comment }: any) =>
           rating.$query(trx).patchAndFetch({ value, comment }),
```

same here

2022-01-05 11:57 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +  if (errors.some(({ err }: any) => err === 403))
```suggestion
  if (errors.some(({ err }) => err === 403))
```

The type inference is fine for this (`number | undefined`), same for two similar ones from line 165.

2022-01-05 11:57 UTC, juhoeerola commented on frontend/src/redux/roadmaps/reducers.ts
> +    });
This is repeated three times, and sufficiently non-trivial to benefit from extracting out. For example:

```ts
const findTask = (taskId: number, roadmaps: Roadmap[]) =>
  roadmaps.reduce<Task | undefined>(
    (found, roadmap) =>
      found ?? roadmap.tasks.find((task) => task.id === taskId),
    undefined,
  );
```

```suggestion
    const parentTask = findTask(taskRating.parentTask, state.roadmaps!);
```

2022-01-05 11:57 UTC, juhoeerola commented on frontend/src/components/modals/RateTaskModal.tsx
> +    const error = edit ? await editRatings(changed) : await addRatings(changed);
```suggestion
    const action = edit
      ? roadmapsActions.patchTaskratings
      : roadmapsActions.addTaskratings;
    const res = await dispatch(action({ ratings: changed, taskId }));
    const error = action.rejected.match(res) && res.payload?.message;
```

Could choose just the action conditionally, which makes the rest straight forward.

2022-01-05 11:57 UTC, juhoeerola commented on frontend/src/components/TaskTableUnrated.tsx
> +  };
```suggestion
  const openModal = (payload: ShowModalPayload) => (e: SyntheticEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dispatch(modalsActions.showModal(payload));
  };

  const openRateModal = openModal({
    modalType: ModalTypes.RATE_TASK_MODAL,
    modalProps: {
      taskId: task.id,
      edit: false,
    },
  });
```

Could make the `openModal()` take `ShowModalPayload`. which would make it applicable for all three handlers.

2022-01-06 10:28 UTC, IidaKainu commented
Thanks again Juho for the insightful and neat refactoring suggestions. Looks like I need to brush up my knowledge on promises
Added fixes and rebased on master

2022-01-06 10:49 UTC, IidaKainu commented
Forgot to edit tests

2022-01-07 11:00 UTC, juhoeerola approved these changes

2022-01-07 11:23 UTC, merged