Edit task ratings
Vincit/VISDOM-Roadmapper pull request #243
Opened 2022-01-13 09:35 UTC by IidaKainu

I diverged from figma's design, since task rating modal displays multiple ratings. With one button to edit ratings, there is no need to find the rating from a (possibly long) list.

Added RoadmapReadUsers permission to Business-role
- Business-users can read either Developer-users or users with at least one same represented customer
- This enables business-users to see who rated listed ratings. It could have been confusing otherwise, as the user could not even identify their own ratings in the list

2022-01-13 13:07 UTC, IidaKainu commented
Moved edit icons to the right side of an editable rating

2022-01-17 12:04 UTC, juhoeerola requested changes
Seems to work as expected

2022-01-18 06:12 UTC, PatricKangasmaki reviewed
Works well, good job 👍 

**Shower thoughts about the design:** One thing that caught my eye was that each of the users task have their own edit buttons even though they all open the same modal where there are all the tasks. The design indicated (at least to me) that I would just change the rating of that exact task. If there was, lets say 100, ratings, it could be frustrating to scroll though all those in the modal just to find the one that you wanted to edit. On the other hand, editing all at the same time is needed if you actually wanted to change possibly tens of ratings at the same time.

![image](https://user-images.githubusercontent.com/80753884/149879555-44078fef-b2a6-4049-956c-f7ccba96260c.png)

2022-01-18 08:30 UTC, IidaKainu commented on frontend/src/pages/TaskOverviewPage.tsx
> -      {hasPermission(role, Permission.RoadmapReadUsers) && (
> I'm not quite sure all roles having the permission at the moment justifies this.

Yeah now that it is pointed out, the permission check should be left as it is

2022-01-18 08:37 UTC, IidaKainu commented
Added Juho's suggestions 👍 

> they all open the same modal where there are all the tasks

In last weekly we discussed it can be like this, at least for now

> The design indicated (at least to me) that I would just change the rating of that exact task

I do still agree with this. If we want to change the modal to display only a certain task on edit, I'd add it as another task to do: it requires some logic changes to the modal, which could take a while.

2022-01-18 09:24 UTC, PatricKangasmaki approved these changes

2022-01-18 12:24 UTC, juhoeerola approved these changes

2022-01-19 10:26 UTC, merged