Leave roadmap button
Vincit/VISDOM-Roadmapper pull request #251
Opened 2022-01-21 10:04 UTC by AleksiKytola

2022-01-21 11:06 UTC, IidaKainu requested changes
Found a few suggestions, otherwise looks good to me 👍

2022-01-21 11:06 UTC, IidaKainu commented on server/src/api/roadmaps/roadmaps.controller.ts
> +    Number(ctx.state.user!.id),
I'd add undefined check that's used in many other routes as well
```suggestion
  if (!ctx.state.user) throw new Error('User is required');
  const numDeleted = await Role.query().deleteById([
    Number(ctx.state.user.id),
```

2022-01-21 12:32 UTC, juhoeerola requested changes
The last admin should probably not be able to leave the roadmap. This would otherwise leave ownerless roadmaps floating around.

I think the options for last admin would be:
- delete the whole roadmap
- assign another team member as admin, and then leave

2022-01-21 12:32 UTC, juhoeerola commented on frontend/src/colors.module.scss
> +  mandy_hover: $COLOR_MANDY;
```suggestion
  mandy_hover: $COLOR_MANDY_HOVER;
```

2022-01-21 12:32 UTC, juhoeerola commented on frontend/src/components/UserInfoCard.tsx
> +    (event) => {
```suggestion
    (event: SyntheticEvent) => {
```

For some reason eslint doesn't complain about "implicit any" when wrapped in `useCallback`

2022-01-24 08:23 UTC, AleksiKytola commented on frontend/src/components/UserInfoCard.module.scss
>      background: $COLOR_MANDY;
A good catch, fixed

2022-01-24 09:33 UTC, AleksiKytola commented
Applied stylistic fixes, blocked leaving roadmaps if the current user is the last admin. Rebased.

2022-01-24 13:16 UTC, juhoeerola requested changes
The frontend looks fine, couple fixes/improvements for the server.

The test failure seems to be incorrect assertion.

2022-01-24 13:16 UTC, juhoeerola commented on server/src/api/roadmaps/roadmaps.controller.ts
> +      .first();
```suggestion
      .findById([ctx.state.user!.id, Number(ctx.params.roadmapId)]);
```

Should also check if the role was found

2022-01-24 13:16 UTC, juhoeerola commented on server/src/api/roadmaps/roadmaps.controller.ts
> +    ]);
```suggestion
    const numDeleted = await role.$query(trx).delete();
```

This would avoid duplicating the query criteria from above.

2022-01-24 13:16 UTC, juhoeerola commented on server/src/api/roadmaps/roadmaps.controller.ts
> +    ctx.status = numDeleted == 1 ? 200 : 404;
```suggestion
    ctx.status = numDeleted == 1 ? 200 : 500;
```

This should always be 1, so otherwise a server error might be more appropriate

2022-01-25 11:36 UTC, juhoeerola approved these changes

2022-01-25 11:38 UTC, merged