Adjust task rating max value to 5
Vincit/VISDOM-Roadmapper pull request #261
Opened 2022-01-27 09:00 UTC by AleksiKytola

2022-01-27 09:43 UTC, IidaKainu requested changes
TaskHeatmap vaatinee vielä mukautusta
<img src="https://user-images.githubusercontent.com/80758782/151333187-f96c54b7-b39f-41f7-9a97-f7a11fbf46f8.png" height="400" />

2022-01-27 09:43 UTC, IidaKainu commented on server/tests/taskratings.test.ts
> +      ).id;
```suggestion
      const { taskId, roadmapId: firstRoadmapId } = await getTestRatingData();
```

2022-01-27 13:56 UTC, AleksiKytola commented on server/tests/taskratings.test.ts
> +      ).id;
Tests fixed & task heatmap roughly fixed

2022-01-27 16:17 UTC, IidaKainu requested changes
TaskHeatmap has a seemingly empty, transparent, row. I wonder what's going on? @AleksiKytola @juhoeerola 
<img src="https://user-images.githubusercontent.com/80758782/151398541-0b29a3e0-ede3-423b-ae16-52964c02bb90.png" height="300" />

2022-01-28 09:30 UTC, AleksiKytola commented on frontend/src/components/TaskHeatmap.module.scss
> -  min-height: 423px;
Re-added minimum size limits

2022-01-28 11:01 UTC, juhoeerola commented on frontend/src/components/TaskHeatmap.tsx
> +        frequencies[5 - avgValue][avgWork] += 1;
> TaskHeatmap has a seemingly empty, transparent, row

```suggestion
        frequencies[5 - avgValue][avgWork - 1] += 1;
```

Previously this was off by one logically but the grid had some extra room. Now the work can also go out of bounds of the grid, which creates mostly empty column.

2022-01-28 11:59 UTC, IidaKainu approved these changes
With the inclusion of Juho's suggestion the visualization makes sense 👍

2022-01-28 12:06 UTC, juhoeerola commented
The axis labels could be slightly confusing, as the zero is really outside the grid. Changing that to 1, and moving those labels to the middle of (side of) the corresponding square *might* be clearer.

2022-01-28 12:58 UTC, merged