Other email views
Vincit/VISDOM-Roadmapper pull request #276
Opened 2022-02-10 13:19 UTC by PatricKangasmaki

2022-02-10 14:00 UTC, PatricKangasmaki commented
Adds emails:
 - Project invitation
 - Email verification

Follows the pattern created by the pull request: Forgot password email #271 and should be reviewed only after that one has been approved.

2022-02-16 14:32 UTC, PatricKangasmaki commented
Removed test routes and rebased on master.

2022-02-23 10:09 UTC, juhoeerola requested changes

2022-02-23 10:09 UTC, juhoeerola commented on frontend/src/components/emails/ProjectInvitationEmail.tsx
> +        <i>Don’t want to join the project? You can ignore this message..</i>
```suggestion
        <i>Don’t want to join the project? You can ignore this message.</i>
```

2022-02-24 09:42 UTC, PatricKangasmaki commented
> This could be moved to e.g. the EmailTemplate module as a higher order component, as it starts to be duplicated quite a few times.

Great point, added that. I renamed htmlBox and improved its' styling a bit as well. And also merged the other PR here which had task rating notification emails, I felt like it didn't really need its own branch when it is basically doing the same thing as these other email views, just different texts

2022-02-24 09:58 UTC, juhoeerola approved these changes
👍

2022-02-25 08:51 UTC, merged