Correctly display unrated tasks count in team members list
Vincit/VISDOM-Roadmapper pull request #308
Opened 2022-03-07 08:23 UTC by AleksiKytola

Previously the row displayed the count of tasks filtered by `isUnrated`, effectively displaying the # of unrated tasks missing from representatives (the count that is used in PO's dashboard and tasklist) instead of the count of the tasks unrated specifically by the PO themself.

2022-03-07 09:02 UTC, juhoeerola requested changes
The old count is also used in the sorting. This should be ok to just update, as there are no other users for it

https://github.com/Vincit/VISDOM-Roadmapper/blob/4a7a85c95788d715cf7c27a55765cce6b614a47f/frontend/src/utils/SortRoadmapUserUtils.ts#L23-L28

2022-03-08 07:26 UTC, AleksiKytola commented
> The old count is also used in the sorting. This should be ok to just update, as there are no other users for it
> 
> https://github.com/Vincit/VISDOM-Roadmapper/blob/4a7a85c95788d715cf7c27a55765cce6b614a47f/frontend/src/utils/SortRoadmapUserUtils.ts#L23-L28

Separated the unrated tasks count into its own util and used it in both places now

2022-03-08 08:58 UTC, juhoeerola requested changes

2022-03-08 08:58 UTC, juhoeerola commented on frontend/src/utils/SortRoadmapUserUtils.ts
> +            unratedTasksByUserCount(tasks, user, roadmapId, customers),
```ts
export const userSort = (
  roadmapId?: number,
  tasks?: Task[],
  customers?: Customer[],
) => (type: UserSortingTypes | undefined): SortBy<RoadmapUser> => {
```

Now the `users` parameter is unused, and should be removed

2022-03-08 12:18 UTC, juhoeerola approved these changes

2022-03-08 13:36 UTC, merged