Add updatedAt & lastEditedBy to task model & schema
Vincit/VISDOM-Roadmapper pull request #353
Opened 2022-03-28 08:52 UTC by AleksiKytola

2022-03-28 12:24 UTC, IidaKainu requested changes
Pieniä huomioita, muuten vaikuttaa mun puolesta hyvältä

2022-03-28 12:24 UTC, IidaKainu commented on frontend/src/redux/roadmaps/types.ts
> +  lastModifiedByUserId: number;
Pitäisikö tän olla nimeltä lastUpdatedByUserId ja nullable?

2022-03-28 12:24 UTC, IidaKainu commented on frontend/src/redux/roadmaps/types.ts
> +  updatedAt: string;
Tämä voi myös olla null

2022-03-28 13:36 UTC, AleksiKytola commented
Applied fixes from comments

2022-03-29 06:05 UTC, IidaKainu approved these changes
👍

2022-03-29 07:55 UTC, merged