Add milestone completion to planner
Vincit/VISDOM-Roadmapper pull request #381
Opened 2022-04-17 12:20 UTC by IidaKainu

Milestone is considered completed, when all its tasks are completed.
Possibility to "complete" a milestone is added (all of its tasks status are changed to completed).

Add completed milestone styles to planner (milestones and roadmap views)

2022-04-20 09:06 UTC, juhoeerola requested changes
Seems to work well

suggestion mostly on simplifying the threading of "completed" through the components

2022-04-20 09:06 UTC, juhoeerola commented on frontend/src/pages/MilestonesEditor.tsx
> +              );
The function could also be used here

2022-04-21 09:07 UTC, IidaKainu commented
Thanks for the clarification: I think I now got what you were after (+ I understand better how BlockGraph works)

2022-04-22 08:34 UTC, juhoeerola approved these changes
Looks good 👍

2022-04-22 08:34 UTC, juhoeerola commented on frontend/src/components/BlockGraph.tsx
> +                [css.completed]: completed && completed(item),
```suggestion
                [css.completed]: completed?.(item),
```

The `?.` operator can also be used for calling nullable functions, or indexing with square brackets `obj?.[key]`

2022-04-22 08:46 UTC, merged