Planner dependency conflicts
Vincit/VISDOM-Roadmapper pull request #385
Opened 2022-04-25 13:39 UTC by juhoeerola

Implemented in this PR:
- show warning about unmet dependency order
  - tooltip with placeholder link
- show relations of the moved task(s) when dragging task or milestone

Not implemented:
- relation modal linked from the warning tooltip
- correct task measuring (maybe #397)

2022-05-04 12:47 UTC, IidaKainu requested changes
Looks great so far 🔥 
Few minor things could be changed
Furthermore, I found checkBadRelations quite dense (in 'there is a lot happening' way) to read and keep track of what is going on, especially in the end when checking for badRelations. Some of this could be attributed to my lack of sleep though. Still, it would be great if its readability could be improved - maybe by splitting smaller parts to some descriptive functions.

2022-05-05 10:42 UTC, juhoeerola commented
Removed unused `possibleVersions` field

2022-05-05 14:01 UTC, juhoeerola commented on frontend/src/components/SortableTask.tsx
> +}) => {
I did consider, but I'm not sure about the effect on readability.

Anyway, switched to earlier null-returns. How do you find that now?

2022-05-06 07:48 UTC, IidaKainu commented on frontend/src/components/SortableTask.tsx
> +}) => {
There's less nesting now, which I think is better 👍

2022-05-06 08:05 UTC, IidaKainu approved these changes
> Removed unused possibleVersions and versionIndex fields, and related code from the bad relation check

> I shuffled things around a little, and named more things

Both of these help with the clarity of checkBadRelations, looks good

2022-05-06 12:01 UTC, merged