Small rating table fixes
Vincit/VISDOM-Roadmapper pull request #412
Opened 2022-05-16 08:18 UTC by IidaKainu

Render newlines and set max height higher

2022-05-16 12:12 UTC, juhoeerola commented
I noticed that there seems to be no limit for the height of the comment box.
Now that newlines are rendered the box is more likely to grow "too much" vertically, so maybe we could limit it a bit.

2022-05-17 08:53 UTC, IidaKainu commented
Added a limit, hopefully it is not too restricting.

2022-05-17 10:51 UTC, juhoeerola requested changes

2022-05-17 10:51 UTC, juhoeerola commented on frontend/src/components/RatingTable.module.scss
> +  overflow: hidden;
> hopefully it is not too restricting

Why not make it scrollable?

```suggestion
  overflow-y: auto;
```

2022-05-17 11:04 UTC, IidaKainu commented on frontend/src/components/RatingTable.module.scss
> +  overflow: hidden;
Good point

2022-05-17 11:19 UTC, juhoeerola approved these changes
👍

2022-05-17 11:35 UTC, merged