Register page
Vincit/VISDOM-Roadmapper pull request #42
Opened 2021-05-12 08:18 UTC by PatricKangasmaki

View for registration page and translations

2021-05-14 06:52 UTC, AleksiKytola commented on frontend/src/pages/RegisterPage.tsx
> +            return setErrorMessage(t('This email is already in use.'));
Tässä tarvinnee myös tarkistaa tuleeko varoitus formatointivirheestä vai siitä että email on jo käytössä

2021-05-14 07:03 UTC, AleksiKytola requested changes
Hyvältä näyttää tota pikkuvirhettä lukuunottamatta. Noi 11 committia voisi rebasella squashata yhteen ennen mergeä.

2021-05-14 11:21 UTC, juhoeerola commented on frontend/src/pages/RegisterPage.module.scss
> +  letter-spacing: -0.03em;
Nämä fontti tyylit voisi ottaa jaetusta typography.scss tiedostosta.
Se on lisätty vasta commitissa 69ab54aca2113ec56ccf3d1bda25c2277a8be123, joten rebase olisi tarpeen

2021-05-14 11:28 UTC, juhoeerola commented
Tuohon kuuluu vielä tuo sama footer kuin login sivullakin, se on vain figmassa jäänyt piiloon

2021-05-20 11:47 UTC, AleksiKytola approved these changes

2021-05-20 11:47 UTC, merged