Add edition for roadmap name and description
Vincit/VISDOM-Roadmapper pull request #421
Opened 2022-05-18 08:21 UTC by IidaKainu

Takes advantage of overviewContent. Not necessarily in align with the look of the settings-page, but gets the job done.

2022-05-18 09:26 UTC, PatricKangasmaki approved these changes
😄

2022-05-18 12:58 UTC, juhoeerola requested changes
I think the settings page definitely needs some nicer look to it, and I'm not sure if the `OverviewContent` will fit to that. But I don't think it's worth speculating too much now.

The functionality seems solid 👍

2022-05-18 12:58 UTC, juhoeerola commented on frontend/src/pages/ConfigurationPage.tsx
> +  const roadmap = roadmaps?.find(({ id }) => id === roadmapId);
```suggestion
  const { data: roadmap } = apiV2.useGetRoadmapsQuery(undefined, {
    skip: !roadmapId,
    ...selectById(roadmapId),
  });
```

Could select by id directly from the query, and skip when no id is present.

2022-05-20 07:18 UTC, IidaKainu commented
> Could select by id directly from the query, and skip when no id is present.


Neat, added

2022-05-20 09:52 UTC, juhoeerola approved these changes

2022-05-20 09:55 UTC, merged