Permission checks
Vincit/VISDOM-Roadmapper pull request #43
Opened 2021-05-14 11:54 UTC by IidaKainu

2021-05-14 13:32 UTC, juhoeerola commented on server/src/utils/isCurrent.ts
> +    requirePermission(Permission.TaskEditOthers)
`requirePermission()` palauttaa middleware funktion, eli boolean kontekstissa se evaluoituu aina todeksi
`hasPermission()` on puolestaan tähän käyttötarkoitukseen sopiva

```suggestion
    hasPermission(ctx, Permission.TaskEditOthers)
```

2021-05-14 13:38 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +        dimension: dimension,
Dimensiota ei varmaankaan pitäisi pystyä muuttamaan

2021-05-14 13:47 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +
Oikeudet tulisi tarkistaa dimension mukaisesti:
- TaskRatingDimension.BusinessValue vaatii Permission.TaskValueRate
- TaskRatingDimension.RequiredWork vaatii Permission.TaskWorkRate

Sama patch reitissä, mutta siinä pitää ottaa huomioon pathcattavan ratingin dimensio

2021-05-14 14:05 UTC, juhoeerola commented on server/src/utils/isCurrent.ts
> +  if (found) {
Nämä isCurrent* funktiot, jotka käyvät tietokannan puolella, voisivat sopia paremmin controllerissa toteutettaviksi.
Silloin tarpeelliset tarkistukset pystyy tekemään samassa transaktiossa toimenpiteen kanssa, ja monessa tilanteessa riittää vain lisätä queryyn sovaltuva `.andWhere()` ehto.

2021-05-17 07:19 UTC, AleksiKytola requested changes

2021-05-17 07:19 UTC, AleksiKytola commented on server/src/api/roadmaps/roadmaps.routes.ts
> +  isCurrentRoadmap,
Tämän isCurrentRoadmap varmistuksen voisi tehdä joka paikassa samalla tavalla. Nyt jossain on tämä middleware ja jossain on vaan "pakotettu" toi roadmapId oikeaksi tähän tapaan. Itse suosin ehkä tuota alla olevaa tapaa mielummin kuin middlewarea

```
const task = await Task.query().insertAndFetch({
    ...others,
    roadmapId: Number(ctx.params.roadmapId),'})
```

2021-05-17 07:19 UTC, AleksiKytola commented on server/src/api/tasks/tasks.controller.ts
```
  const updated = await Task.query().patchAndFetchById(
    Number(ctx.params.taskId),
    {
      ...others,
      roadmapId: Number(ctx.params.roadmapId),
    },
  );
```

Tässä taitaa olla mahdollista laittaa parametriksi roadmapid joka ei sisällä kyseistä taskia ja käyttää sen oikeuksia ton taskin patchaamiseen, sillä patchattava taski haetaan pelkän taskId perusteella.

Tähän täytynee lisätä WHERE millä tarkistetaan että taskissa on annettu id JA roadmapId

2021-05-17 07:19 UTC, AleksiKytola commented on server/src/utils/isCurrent.ts
> +export const isCurrentTaskCreator = async (
Tuli mieleen että nimen voisi muuttaa
isCurrentTaskCreator antaisi uskoa että tarkastetaan että käyttäjä omistaa taskin ja sillä se, mutta tuo tarkastaa että onko taskiin oikeus muokata (eli onko oma taski TAI onko oikeudet muokata muiden omia) nimi vois olla jotain tyyliin
hasTaskPermission tms.

2021-05-17 07:49 UTC, juhoeerola commented on server/src/api/users/users.controller.ts
> +    id: ctx.request.body.id,
tuon id:nhän voi jättää kokonaan pois, kun params.id:llä jo haetaan päivitettävä rivi

2021-05-17 10:50 UTC, IidaKainu commented
Lisäsin tähän kaikki muutospyynnöt.
Kirjoitin nyt monet permissiocheckit kyselyissä tähän tapaan:
https://medium.com/@mikeh91/conditionally-adding-keys-to-javascript-objects-using-spread-operators-and-short-circuit-evaluation-acf157488ede

Jos näyttää vaikealukuiselta niin voin keksiä niihin jotain muuta

2021-05-18 10:16 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +          hasPermission(ctx, Permission.TaskWorkRate))) && {
Oikeudet täytyy tarkistaa ennen queryä, nyt heittää validation erroria puuttuvista kentistä, jos oikeuksia ei ole.

Insertissä täytyy myös poistaa mahdollinen `id` kenttä, koska se halutaan tietokannan generoimana.

2021-05-18 11:09 UTC, juhoeerola commented on server/src/api/taskratings/taskratings.controller.ts
> +        createdByUser: Number(ctx.state.user.id),
parentTask pitäisi myös ottaa route parametreista

samaten PATCH reitissä, sitä ei varmaankaan pitäisi voida muuttaa

2021-05-19 11:41 UTC, juhoeerola approved these changes
Hyvältä näyttää 👍

2021-05-19 13:00 UTC, merged