Add navigation from task overview to planner
Vincit/VISDOM-Roadmapper pull request #431
Opened 2022-05-24 08:02 UTC by IidaKainu

If user has navigated to TaskOverview from RelationsModal link, the back-button takes the user back to MilestonesEditor

2022-05-24 08:04 UTC, IidaKainu commented
Though, should the (same) RelationsModal be open when navigating back to MilestonesEditor? I could make that happen

2022-05-25 09:11 UTC, juhoeerola requested changes
There are links to the task overview from elsewhere also:
- the individual tasks in the relation "modal"
- the tasks in roadmap tab sidebar (this won't stay open with the current implementation)

The `TaskRow` (in TaskTable.tsx) component links to the task overview and could also set the back ref (when it's not on the task overview page already).

---

It would be neat if we could use the history stack for this (instead of extra redux state), but that would be a bit tricky when browsing between the tasks using the arrows on the overview page.

2022-05-25 09:11 UTC, juhoeerola commented on frontend/src/redux/roadmaps/types.ts
> +  fromMilestonesEditor?: string;
I think the more relevant information is that this is the "back href for task overview page", which should be in the name. Currently the name doesn't really tell much, unless you already know what it is supposed to mean.

This is even more apparent when handling the other locations.

2022-05-26 08:56 UTC, IidaKainu commented
Took your feedback into consideration and [implemented this with another strategy](https://github.com/Vincit/VISDOM-Roadmapper/pull/439).

2022-05-26 08:56 UTC, closed without merging