Fix compile warnings in frontend
Vincit/VISDOM-Roadmapper pull request #472
Opened 2022-06-10 08:38 UTC by IidaKainu

2022-06-10 09:10 UTC, juhoeerola requested changes
Great 👍 
Just couple suggestions for simplifications

2022-06-10 09:10 UTC, juhoeerola commented on frontend/src/components/MissingRatings.tsx
> +          missingDevRatings.map(({ email }) => (
```suggestion
        {missingDevRatings?.map(({ email }) => (
```

I don't think this was changed in this PR, but why not add it

2022-06-10 09:10 UTC, juhoeerola commented on frontend/src/components/UserInfoCard.tsx
>      ),
I'd rather just move this outside the `UserInfoCard` component

```suggestion
    Title,
```

```tsx
const Title = () => (
  <h2>
    <Trans i18nKey="Projects" />
  </h2>
);
```

2022-06-13 07:26 UTC, IidaKainu commented
> Just couple suggestions for simplifications

Added, thanks 👍

2022-06-13 07:40 UTC, juhoeerola approved these changes

2022-06-13 07:47 UTC, merged