Add new modal and styling for task map info-tooltip
Vincit/VISDOM-Roadmapper pull request #479
Opened 2022-06-15 08:22 UTC by PatricKangasmaki

Task map info matches Figma now. I also added a new icon and description for zooming in and out (it wasn't in Figma, opinions if it's needed are appreciated). 

I'd also like to hear opinions on these two approaches I took:
- I separated the data of `Overview` and `Actions` to their own file as they turned out to be really long (120 lines of code). Having them in the main modal file made it + 270 lines and it felt really cluttered.
- CSS file is split to sections by comments as it started to get hard to read.

2022-06-15 08:41 UTC, PatricKangasmaki commented on frontend/src/components/TaskMap.module.scss
> +  padding-bottom: 111px; // Margin top pushes the bottom of the drawer out of the picture without padding.
Latest push only changed this:

```
margin-top: 115px -> 111px;
padding-bottom: 115px -> 111px;
```

(if you look closely, the info-drawer is a few pixels lower than the background):
![image](https://user-images.githubusercontent.com/80753884/173783063-553141ce-1001-4940-81bd-7b5bdbdf7656.png)

2022-06-15 09:27 UTC, IidaKainu commented
The width of the hr-elements (or the lines, did not yet look at the code) could be constricted, they are currently making the modal horizontally scrollable
![image](https://user-images.githubusercontent.com/80758782/173793546-897578c3-032e-4456-a5f3-83d5333a663c.png)

2022-06-15 09:48 UTC, IidaKainu commented
Suggestion: can we add the info icon in the modal header (like the relations icon in planner)? It could connect the modal to the disappearing info button better...maybe
![image](https://user-images.githubusercontent.com/80758782/173795378-72d9b006-b39f-495c-aa76-8cae98812588.png)

2022-06-15 15:28 UTC, PatricKangasmaki commented
Added both suggestions 👍

2022-06-16 06:58 UTC, IidaKainu commented
The positioning of the modal and task map control icons break a bit when navbar is wraps to two lines. However, task map is realistically usable only in a wider viewport, so no need to spend much time on this if it isn't easily fixable.
![image](https://user-images.githubusercontent.com/80758782/174010321-2931d475-7493-4a61-926e-1096abac497d.png)

2022-06-16 12:15 UTC, IidaKainu requested changes

2022-06-20 16:02 UTC, IidaKainu approved these changes
👍 

> I didn't touch this for now. I think it's better to use our limited resources for other things right now since this only happens on a viewport that's too narrow to use the whole page and even then, the breaking is so small that it doesn't really have any other effect than the small breaking of the correct height of the drawer (Not blocking anything etc.)

Sounds like a good decision

2022-06-20 17:49 UTC, merged