Fix add more colors for planner chart
Vincit/VISDOM-Roadmapper pull request #488
Opened 2022-06-22 09:49 UTC by AnttiVaarala

If there's less colors than milestones they start to repeat themselves

2022-06-22 09:54 UTC, IidaKainu requested changes

2022-06-22 09:54 UTC, IidaKainu commented on frontend/src/components/PlannerChart.tsx
> +  '#EA9128',
Maybe these should be added to colors.module.scss

2022-06-22 11:17 UTC, IidaKainu commented on frontend/src/components/PlannerChart.tsx
> +  '#EA9128',
And noting just to remember what was discussed in weekly: the values can be darkened

2022-06-30 17:20 UTC, PatricKangasmaki commented on frontend/src/components/PlannerChart.module.scss
> +  flex-direction: row;
This could extend to the class `.layout-row` instead as it has been a default style in this project

2022-06-30 17:20 UTC, PatricKangasmaki commented on frontend/src/components/PlannerChart.module.scss
> +  flex-direction: column;
Same here, `@extend .layout-column`

2022-06-30 17:29 UTC, PatricKangasmaki commented on frontend/src/components/PlannerChart.tsx
> +              strokeWidth={2}
I'd change the strokeWidth to something like 1.5, this value 2 looks a bit too thick in my opinion. And those other two places as well where to strokeWidth was at 2

2022-06-30 17:37 UTC, PatricKangasmaki commented
Few suggestions above. Otherwise this is looking great 👍 I will not request changes now as I won't be able to re-review anymore after this but feel free to disagree with my points as well and apply what you feel like are good changes

2022-07-01 08:57 UTC, IidaKainu commented
Sorry Antti, I went ahead and added Patric's suggestions, because the summer vacation is waiting 🌞

2022-07-01 08:57 UTC, IidaKainu commented
Sorry Antti, I went ahead and added Patric's suggestions, because the summer vacation is waiting 🌞

2022-07-01 08:58 UTC, IidaKainu approved these changes

2022-07-01 08:58 UTC, merged