Task attachments
Vincit/VISDOM-Roadmapper pull request #495
Opened 2022-06-30 09:32 UTC by patricvincit

2022-06-30 13:48 UTC, IidaKainu requested changes
A bit of a hasty review; maybe I'll look through this once more tomorrow.

Added a commit with API improvements, but they ended up escalating a bit. Feel free to review it 😄

2022-06-30 13:51 UTC, IidaKainu commented
Realized the delete attachment modal displays [object Object]. Probably my fault, I'll try to fix it soon

2022-06-30 17:17 UTC, PatricKangasmaki commented on frontend/src/components/modals/AddTaskModal.tsx
> +      );
Yeah, this would do the job as well. Seems like I was thinking way too much about mapping and forgot about basic functionalities 😄

2022-06-30 17:53 UTC, PatricKangasmaki commented
Applied your suggestion about the irrelevant mapping 👍 
> Realized the delete attachment modal displays [object Object]. That's probably my fault  

I fixed this as well, the delete modal passed the attachment object to translation values instead of the attachment property of the object. Your API improvements look great 🔥

2022-06-30 18:17 UTC, PatricKangasmaki commented
>Also the add task test needs to be updated. I'll try to fix these soon

Fixed this as well now 😄👍

2022-07-01 08:23 UTC, IidaKainu approved these changes

2022-07-01 08:24 UTC, merged