Separate unique and validation errors in registration form
Vincit/VISDOM-Roadmapper pull request #68
Opened 2021-06-03 06:58 UTC by PatricKangasmaki

2021-06-03 11:19 UTC, juhoeerola requested changes

2021-06-03 11:19 UTC, juhoeerola commented on frontend/src/pages/RegisterPage.tsx
> +        }
Tämän voisi kääntää tarkistamaan ensin virheen tyypin, niin on helpompi käsitellä kukin soveltuvalla tavalla, ja lisätä tarvittaessa käsittely uudelle virhetyypille.

ValidationError ja UniqueViolationError lähinnä tarvii käsitellä, muut voivat hyvin vielä mennä geneerisenä server errorina.

Nuo kaksi tyyppiä sisältävät lisäksi `columns` listan virheen aiheuttaneista kentistä, jota voi hyödyntää. Etenkin ValidationError voi sisältää useamman kentän, esim.

```json
{
  "error": "ValidationError",
  "message": "\"email\" should match format \"email\"\n\"password\" should NOT be longer than 72 characters",
  "columns": [
    {
      "column": "email",
      "message": "should match format \"email\""
    },
    {
      "column": "password",
      "message": "should NOT be longer than 72 characters"
    }
  ]
}
```

2021-06-04 07:50 UTC, AleksiKytola commented on frontend/src/pages/RegisterPage.tsx
> +        }
Joo se tais just tulla uutena backendiin et se lähettää ValidationErrorinkin omana tyyppinään eli tyypin ja kolumnit on nyt helpompi tarkistaa

2021-06-07 06:42 UTC, AleksiKytola approved these changes

2021-06-07 10:55 UTC, juhoeerola approved these changes

2021-06-08 07:32 UTC, merged