Customer edition
Vincit/VISDOM-Roadmapper pull request #71
Opened 2021-06-07 07:22 UTC by IidaKainu

2021-06-07 07:47 UTC, IidaKainu commented on frontend/src/App.tsx
> +    secondary: { main: '#0ec679' },
Figman checkboksit näyttivät samalta kuin material UI:n, joten otin ne käyttöön. MuiTheme on siis vain valintaruudun värin muuttamiseen: jos on tiedossa parempi tapa tämän tekoon niin ehdottakaa ehdottomasti

2021-06-07 07:47 UTC, IidaKainu commented on frontend/src/components/forms/RatingsButton.module.scss
> +    fill: $COLOR_AZURE;
Figmasta löytyi hover värit ikoneille

2021-06-07 07:47 UTC, IidaKainu commented on frontend/src/components/modals/EditCustomerModal.tsx
> +      .map((obj) => ({ ...obj, checked: false })),
Tämä on oikeastaan turha, sillä useEffect hoitaa asian. En keksinyt miten saisin alustettua useStaten odottamaan epämääräistä RoamapUser[] + checked -tyyppiä

2021-06-07 10:05 UTC, AleksiKytola commented on frontend/src/components/modals/EditCustomerModal.tsx
> +              </div>
Selaimen konsoli saattanee herjata tästä, mapatessa performancen takia laitettava komponentille yksilöllinen "key" prop jonka perusteella react osaa optimoida renderöintiä

2021-06-07 10:35 UTC, AleksiKytola requested changes

2021-06-07 10:35 UTC, AleksiKytola commented on frontend/src/components/modals/EditCustomerModal.tsx
> +      .map((obj) => ({ ...obj, checked: false })),
Monia tapoja löytyy. Jos haluaa tuolla tavalla tehdä voi esim extendata Roadmapuseria siten että sillä on checked-property
`type CheckableUser = RoadmapUser | { checked: boolean };`
ja tallentaa stateen CheckableUser[]

toinen lähestymistapa on sen sijaan tallentaa stateen vain lista user ID:eitä jotka on checkattu
`const [representatives, setRepresentatives] = useState<number[]>([]);`

2021-06-07 10:35 UTC, AleksiKytola commented on frontend/src/components/modals/EditCustomerModal.tsx
> +    setRepresentatives(copy);
Ei mitenkään väärin. Vinkkaan vain että näinkin voi kopioida (jokatapauksessa kummallakaan tavalla ei käsittääkseni muuten itse sisältö syväkopioidu vaan pelkät referenssit objekteihin) 
`const copy = [...representatives]`

typescriptillä  taitaa saada tehtyä optionaalina
`const copy = [...representatives?]`
tai vähintäänkin joku näistä toimii riippuen halutaanko arvon puuttuessa undefined vai tyhjä array
`const copy = [...(representatives || [])]`
`const copy = [...(representatives ?? [])]`
`const copy = (representatives && ...representatives)`

2021-06-07 10:35 UTC, AleksiKytola commented on frontend/src/redux/user/types.ts
> +}
Tämä taisi olla jo backendissä mutta taisi olla tarkoitus refaktoroida ennen pitkää /shared/ kansioon

2021-06-07 12:29 UTC, IidaKainu commented on frontend/src/redux/user/types.ts
> +}
Kopioin tuon väliaikaisesti fronttiin, jotta modaalissa voi tarkastella onko user.type admin tai business

2021-06-07 12:33 UTC, IidaKainu commented on frontend/src/components/modals/EditCustomerModal.tsx
> +    setRepresentatives(copy);
Jostain syystä selkein vaihtoehto
`[...representatives?] `
Ei toiminut. Vaihdoin kuitenkin alempiin vaihtoehtoihin

2021-06-07 12:50 UTC, IidaKainu commented
(force-pushissa vaan tyylimuutoksia)

2021-06-07 13:24 UTC, juhoeerola requested changes

2021-06-07 13:24 UTC, juhoeerola commented on frontend/src/utils/CustomerUtils.ts
> +};
Tähän olisi hyvä lisätä jokin raja yrityksille (muukin kuin implisiittinen max call stack size), ettei jää ikuiseen looppiin. Tuohon taitaa mahtua kuitenkin rajallinen määrä arvoja halutulla erotuksella muutenkin.

Lisäksi täytyy toki olla jokin fallback, jos ei sopivaa väriä löydy.

Ps. `[].some` on predikaatti versio `[].find`:lle, joka voi siten olla semanttisesti parempi vaihtoehto tällaisessa käytössä.

2021-06-08 08:59 UTC, juhoeerola commented
> En vielä keksinyt, mitä tekisi jos sopivaa väriä ei löydy. Tällä hetkellä palauttaa (luultavimmiten) jo käytetyn värin.

Yksi mahdollisuus on ottaa suurin tyhjä intervalli jo käytettyjen hue arvojen välillä ja valitsee siitä puolivälin.

Mutta random värikin lienee ihan ok, sillä käyttäjällä on kuitenkin vaihtoehtona valita itse, jos ei väri miellytä.

2021-06-09 09:43 UTC, merged