Planner check ratings
Vincit/VISDOM-Roadmapper pull request #77
Opened 2021-06-14 09:47 UTC by PatricKangasmaki

Tehty missing-task-ratings haaran päälle, kaikki planner-check-ratingsiin liittyvät muutokset tiedostossa 'frontend/src/pages/MilestonesEditor.tsx'

2021-06-14 13:51 UTC, juhoeerola requested changes

2021-06-14 13:51 UTC, juhoeerola commented on frontend/src/pages/MilestonesEditor.tsx
> +      const developers = allUsers?.filter((user) => user.type === 279715);
```suggestion
      const developers = allUsers?.filter((user) => user.type === RoleType.Developer);
```

Löytyy `redux/user/types`

2021-06-14 13:51 UTC, juhoeerola commented on frontend/src/pages/MilestonesEditor.tsx
> +          ratedTasks.push(task);
```suggestion
        const unratedByDeveloper = developers?.some(
          (developer) => !allRatings.includes(developer.id),
        );

        if (unratedByCustomer?.length === 0 && unratedByDeveloper === false)
          ratedTasks.push(task);
```

Ei tarvitse välttämättä kaikkia käydä läpi, tällä saa saman logiikan mutta short circuiting versiona

2021-06-16 09:41 UTC, juhoeerola commented on frontend/src/pages/MilestonesEditor.tsx
> +          ratedTasks.push(task);
Nyt muutoksen jälkeen `!unratedByDeveloper` eroaa `unratedByDeveloper === false` (ja aikaisemmasta `unratedByDeveloper?.length === 0`) ehdosta, jos `developers === undefined`.

Jos tämä muutos on muun logiikan puolesta okei, niin 👍

2021-06-17 10:38 UTC, PatricKangasmaki commented on frontend/src/pages/MilestonesEditor.tsx
> +          ratedTasks.push(task);
Kävin testaamassa ja logiikka toimi edelleen uudella muutoksella myös kuten toivottu 👍

2021-06-17 11:52 UTC, juhoeerola approved these changes

2021-06-17 14:38 UTC, merged