UserType to RoleType
Vincit/VISDOM-Roadmapper pull request #83
Opened 2021-06-16 10:59 UTC by IidaKainu

2021-06-17 13:12 UTC, juhoeerola requested changes
Tuolle `UserInfo.type`:n mahdolliselle puuttumiselle täytyy jokin ratkaisu kyllä kehittää. Tällä hetkellä hajottaa melkein kaikki sivut, jos sitä ei ole haettuna.

Yksi mahdollisuus voisi olla hakea se koko rooli lista infoon, ja sitten hakea siitä rooli valitun roadmapin mukaan.

2021-06-18 14:18 UTC, juhoeerola commented
> Yksi mahdollisuus voisi olla hakea se koko rooli lista infoon, ja sitten hakea siitä rooli valitun roadmapin mukaan.

Tarvitsin itse käyttäjän kaikkia rooleja niin lisäsin ne `ctx.state.user`iin, jolloin ne löytyvät myös `userInfo`sta.
Cherry-pick tuo kommitti, jos tarvit https://github.com/Vincit/VISDOM-Roadmapper/pull/87/commits/9633ea18b29e37489af56036b1407ba67ca5dc4a

2021-06-21 08:18 UTC, IidaKainu commented
Kaikkien roolien hakeminen userInfoon vaikutti hyvältä ratkaisulta. Kiitos cherry-pick vinkistä!
Poistin backendistä roadmap-kohtaisen whoAmI-reitin, jää turhaksi kun tiettyä roolia ei tarvitse etsiä

Scheman muutokset siirretty omaan migraatioonsa
DashboardPagessa ei enää haeta userInfoa, joten ikuinen looppi ei ole ongelma

2021-06-21 09:45 UTC, juhoeerola approved these changes

2021-06-21 11:08 UTC, merged