Require customer color
Vincit/VISDOM-Roadmapper pull request #84
Opened 2021-06-17 10:51 UTC by IidaKainu

2021-06-17 11:42 UTC, AleksiKytola requested changes
Diffissä ei näy enkä kaivellut koodia mutta täytyy myös varmistaa että customeria luodessa sinne tulee jokin väri, tässä diffissä näen vain muutoksia edit-modaliin. Saako addcustomermodal jonkin värin alkuarvon?

Lisäksi tuon migraation muutoksen voisi siirtää omaan migraatioon `knex migrate:make migration_name`

2021-06-17 11:42 UTC, AleksiKytola commented on server/src/migrations/20210510160632_addCustomerModel.ts
> +      table.string('color', 7).notNullable();
Migraatioita ei saisi muuttaa vaan täytyisi tehdä uusi joka muokkaa tuota listaa. Nämä ovat eräänlainen aikajana database schemalle ja knex tallentaa tietokantaan mitkä migraatiot se on jo ajanut. Tässä tapauksessa se ei paljoa vaikuttaisi koska staging database ajetaan vielä kerran alas ja devaus databaset käynnistellään ja sammutellaan edestakaisin. Mutta jos tuotannossa olisi jo joku database mihin migraatiot olisi ajettu, ei tämä muutos tulisi voimaan koska knex katsoisi että on jo ajanut tämän migraation

2021-06-18 07:07 UTC, IidaKainu commented on server/src/migrations/20210510160632_addCustomerModel.ts
> +      table.string('color', 7).notNullable();
Kiitos selityksestä: migraatioiden toiminnasta olikin jo puhuttu, mutta vasta nyt sisäistin asian! 

Laitoin oman migraation muutokselle. Customerin lisäämiselle ei ole vielä toteutettu modaalia, joten sen vuoksi muutoksia ei löydy 👍

2021-06-18 08:19 UTC, AleksiKytola approved these changes

2021-06-18 08:19 UTC, merged