Update client weights styles according to figma
Vincit/VISDOM-Roadmapper pull request #85
Opened 2021-06-17 12:19 UTC by IidaKainu

Sliderin tyylit päivitetty ja listaan lisätty customerin väri

2021-06-17 13:32 UTC, juhoeerola requested changes
Default weight:in voisi laittaa vielä osumaan sliderin stepin kohdalle

2021-06-17 13:32 UTC, juhoeerola commented on frontend/src/components/forms/Slider.tsx
> +    color: '#0ec679',
```suggestion
const COLOR_EMERALD = '#0ec679';

export const Slider = withStyles({
  root: {
    color: COLOR_EMERALD,
```

Voisi nimetä nämä värit, niin on sitten helpompi yhdistää `shared.scss`:n vastaavaan väriin.

Scss muuttujia ei taida pystyä suoraan käyttämään

2021-06-18 05:37 UTC, PatricKangasmaki commented on frontend/src/components/forms/Slider.tsx
> +    color: '#0ec679',
Jos haluaa koittaa saada scss muuttujat suoraan, niin tämä voisi toimia, mutta siinä täytyisi käydä vähän configeja muuttamassa ja exportata `shared.scss` tiedostosta muuttujat:
https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript

2021-06-18 09:17 UTC, IidaKainu commented on frontend/src/components/forms/Slider.tsx
> +    color: '#0ec679',
Ilmeisesti jos scss-filun nimeää moduulina niin voi importtaa muuttujia ilman mitään ekstraa. Laitoin värit omaan tiedostoon (sivun tyylit räjähti jostain syystä kun muutin shared.scss -> shared.module.scss)

2021-06-18 09:44 UTC, IidaKainu commented
> Default weight:in voisi laittaa vielä osumaan sliderin stepin kohdalle

Muistankohan oikein, et Teemu mainitsi oletusweightiksi 0:n? Aattelin tässä, etten koske arvoihin jos niihin tulee muutoksia sun trellokortin kautta 🤔 Tai siis jos oletusarvo tulee olemaan 0, niin sen jälkeen weightit osuu aina sliderin stepeille

2021-06-18 10:32 UTC, juhoeerola commented
```ts
  const weight = (id: number) => {
    const customer = customerWeights.find(
      ({ customerId }) => customerId === id,
    );
    return customer ? customer.weight : 1;  // tämä asettaa oletusarvon (1)
  };
```
Voisihan sen oletusarvon laittaa nollaksi jo tässä kohtaa

2021-06-18 11:01 UTC, IidaKainu commented
Ahaa, enpä huomannut tuota. Muutettu

2021-06-18 11:12 UTC, juhoeerola approved these changes

2021-06-18 11:18 UTC, merged